import { openSans, robotoSlab } from "@/lib/fonts";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react"
import { ThemeProvider } from "@/components/theme-provider";
import ReduxProvider from "@/lib/redux/provider"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${openSans.variable} ${robotoSlab.variable}`}>
      <ReduxProvider>
      <ThemeProvider attribute="class" defaultTheme= "system" enableSystem disableTransitionOnChange>{children}</ThemeProvider>
      </ReduxProvider>
      </body>

    </html>
  );
}
